// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telara.Domain.Data;

#nullable disable

namespace Telara.Domain.Migrations
{
    [DbContext(typeof(TelaraDbContext))]
    [Migration("20260912144554_AddStationOutputTracking")]
    partial class AddStationOutputTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Telara.Domain.Entities.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EquipmentTypes", "dbo");
                });

            modelBuilder.Entity("Telara.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("family_id");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "dbo");
                });

            modelBuilder.Entity("Telara.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("Telara.Domain.Entities.SensorReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("equipment_id");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("facility_id");

                    b.Property<DateTime>("ReadingAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("reading_at_utc");

                    b.Property<string>("ReadingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reading_type");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("sensor_id");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("station_id");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId", "StationId", "EquipmentId", "SensorId", "ReadingAtUtc");

                    b.ToTable("SensorReadings", "dbo");
                });

            modelBuilder.Entity("Telara.Domain.Entities.Station", b =>
                {
                    b.Property<string>("FacilityId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("facility_id");

                    b.Property<string>("StationId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("station_id");

                    b.Property<bool>("IsLoadingDock")
                        .HasColumnType("bit")
                        .HasColumnName("is_loading_dock");

                    b.Property<DateTime?>("LastOperatorActionUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_operator_action_utc");

                    b.Property<string>("NextStationId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("next_station_id");

                    b.Property<decimal?>("TargetOutputPerShift")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("target_output_per_shift");

                    b.HasKey("FacilityId", "StationId");

                    b.HasIndex("FacilityId", "NextStationId");

                    b.ToTable("Stations", "dbo");
                });

            modelBuilder.Entity("Telara.Domain.Entities.StationEquipment", b =>
                {
                    b.Property<string>("FacilityId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("facility_id");

                    b.Property<string>("StationId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("station_id");

                    b.Property<string>("EquipmentId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("equipment_id");

                    b.Property<string>("ActiveInstanceId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("active_instance_id");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("equipment_type_id");

                    b.Property<DateTime?>("LastSensorReadingUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_sensor_reading_utc");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("FacilityId", "StationId", "EquipmentId");

                    b.HasIndex("EquipmentTypeId");

                    b.ToTable("StationEquipment", "dbo");
                });

            modelBuilder.Entity("Telara.Domain.Entities.StationOutputRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("facility_id");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("station_id");

                    b.Property<decimal>("UnitsProduced")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("units_produced");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId", "StationId", "RecordedAtUtc");

                    b.ToTable("StationOutputRecords", "dbo");
                });

            modelBuilder.Entity("Telara.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AssignedRoleId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_role_id");

                    b.Property<string>("AssignedStationEquipmentId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assigned_station_equipment_id");

                    b.Property<string>("AssignedStationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assigned_station_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("AssignedRoleId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("Telara.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Telara.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Telara.Domain.Entities.SensorReading", b =>
                {
                    b.HasOne("Telara.Domain.Entities.StationEquipment", "StationEquipment")
                        .WithMany()
                        .HasForeignKey("FacilityId", "StationId", "EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StationEquipment");
                });

            modelBuilder.Entity("Telara.Domain.Entities.Station", b =>
                {
                    b.HasOne("Telara.Domain.Entities.Station", "NextStation")
                        .WithMany()
                        .HasForeignKey("FacilityId", "NextStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NextStation");
                });

            modelBuilder.Entity("Telara.Domain.Entities.StationEquipment", b =>
                {
                    b.HasOne("Telara.Domain.Entities.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Telara.Domain.Entities.Station", "Station")
                        .WithMany("Equipment")
                        .HasForeignKey("FacilityId", "StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentType");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Telara.Domain.Entities.StationOutputRecord", b =>
                {
                    b.HasOne("Telara.Domain.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("FacilityId", "StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Telara.Domain.Entities.User", b =>
                {
                    b.HasOne("Telara.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("AssignedRoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Telara.Domain.Entities.Station", b =>
                {
                    b.Navigation("Equipment");
                });
#pragma warning restore 612, 618
        }
    }
}
